    #ifndef _FPTR_STRUCT_H_
    #define _FPTR_STRUCT_H_
    struct glfunc_ptrs {
GLvoid ( * glBlendColor)(GLclampf,GLclampf,GLclampf,GLclampf);
GLvoid ( * glBlendEquation)(GLenum);
GLvoid ( * glCopyTexSubImage3D)(GLenum,GLint,GLint,GLint,GLint,GLint,GLint,GLsizei,GLsizei);
GLvoid ( * glDrawRangeElements)(GLenum,GLuint,GLuint,GLsizei,GLenum,GLvoid*);
GLvoid ( * glTexImage3D)(GLenum,GLint,GLint,GLsizei,GLsizei,GLsizei,GLint,GLenum,GLenum,const GLvoid*);
GLvoid ( * glTexSubImage3D)(GLenum,GLint,GLint,GLint,GLint,GLsizei,GLsizei,GLsizei,GLenum,GLenum,const GLvoid*);
GLenum ( * glGetError)(void);
GLvoid ( * glEndQuery)(GLenum);
GLboolean ( * glIsQuery)(GLuint);
GLvoid ( * glBeginQuery)(GLenum,GLuint);
GLvoid ( * glBindBuffer)(GLenum,GLuint);
GLboolean ( * glIsBuffer)(GLuint);
GLvoid ( * glGenQueries)(GLsizei,GLuint *);
GLvoid ( * glDeleteQueries)(GLsizei,const GLuint *);
GLvoid ( * glGenBuffers)(GLsizei,GLuint *);
GLvoid ( * glDeleteBuffers)(GLsizei,const GLuint *);
GLvoid ( * glGetQueryiv)(GLenum,GLenum,GLint *);
GLvoid ( * glGetQueryObjectiv)(GLuint,GLenum,GLint *);
GLvoid ( * glGetQueryObjectuiv)(GLuint,GLenum,GLuint *);
GLvoid ( * glBufferData)(GLenum,GLsizeiptr,GLvoid *,GLenum);
GLvoid ( * glBufferSubData)(GLenum,GLintptr,GLsizeiptr,GLvoid *);
GLvoid ( * glGetBufferSubData)(GLenum,GLintptr,GLsizeiptr,GLvoid *);
GLvoid ( * glGetBufferParameteriv)(GLenum,GLenum,GLint *);
GLvoid * ( * glMapBuffer)(GLenum,GLenum);
GLboolean ( * glUnmapBuffer)(GLenum);
GLvoid ( * glGetBufferPointerv)(GLenum,GLenum,GLvoid **);
GLvoid ( * glGenFencesNV)(GLsizei,GLuint *);
GLvoid ( * glDeleteFencesNV)(GLsizei,const GLuint *);
GLvoid ( * glSetFenceNV)(GLuint,GLenum);
GLboolean ( * glTestFenceNV)(GLuint);
GLboolean ( * glIsFenceNV)(GLuint);
GLvoid ( * glFinishFenceNV)(GLuint);
GLvoid ( * glGetFenceivNV)(GLuint,GLenum,GLint *);
GLvoid ( * glLoadProgramNV)(GLenum,GLuint,GLsizei,const GLubyte *);
GLvoid ( * glGetProgramivNV)(GLuint,GLenum,GLint *);
GLvoid ( * glGetProgramStringNV)(GLuint,GLenum,void *string);
GLvoid ( * glBindProgramNV)(GLenum,GLuint);
GLboolean ( * glIsProgramNV)(GLuint);
GLvoid ( * glGenProgramsNV)(GLsizei,GLuint *);
GLvoid ( * glDeleteProgramsNV)(GLsizei,const GLuint *);
GLvoid ( * glExecuteProgramNV)(GLenum,GLuint,const GLfloat *);
GLvoid ( * glVertexAttribPointerNV)(GLuint,GLint,GLenum,GLsizei,const GLvoid *);
GLvoid ( * glGetVertexAttribPointervNV)(GLuint,GLenum,GLvoid **);
GLvoid ( * glProgramParameter4dNV)(GLenum,GLuint,GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glProgramParameter4fNV)(GLenum,GLuint,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glProgramParameter4dvNV)(GLenum,GLuint,const GLdouble *);
GLvoid ( * glProgramParameter4fvNV)(GLenum,GLuint,const GLfloat *);
GLvoid ( * glGetProgramParameterdvNV)(GLenum,GLuint,GLenum,GLdouble *);
GLvoid ( * glGetProgramParameterfvNV)(GLenum,GLuint,GLenum,GLfloat *);
GLvoid ( * glProgramParameters4dvNV)(GLenum,GLuint,GLuint,const GLdouble *);
GLvoid ( * glProgramParameters4fvNV)(GLenum,GLuint,GLuint,const GLfloat *);
GLvoid ( * glVertexAttrib1dNV)(GLuint,GLdouble);
GLvoid ( * glVertexAttrib1fNV)(GLuint,GLfloat);
GLvoid ( * glVertexAttrib1sNV)(GLuint,GLshort);
GLvoid ( * glVertexAttrib2dNV)(GLuint,GLdouble,GLdouble);
GLvoid ( * glVertexAttrib2fNV)(GLuint,GLfloat,GLfloat);
GLvoid ( * glVertexAttrib2sNV)(GLuint,GLshort,GLshort);
GLvoid ( * glVertexAttrib3dNV)(GLuint,GLdouble,GLdouble,GLdouble);
GLvoid ( * glVertexAttrib3fNV)(GLuint,GLfloat,GLfloat,GLfloat);
GLvoid ( * glVertexAttrib3sNV)(GLuint,GLshort,GLshort,GLshort);
GLvoid ( * glVertexAttrib4dNV)(GLuint,GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glVertexAttrib4fNV)(GLuint,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glVertexAttrib4sNV)(GLuint,GLshort,GLshort,GLshort,GLshort);
GLvoid ( * glVertexAttrib4ubNV)(GLuint,GLubyte,GLubyte,GLubyte,GLubyte);
GLvoid ( * glVertexAttrib4ubvNV)(GLuint,GLubyte *);
GLvoid ( * glVertexAttrib4dvNV)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib4fvNV)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib4svNV)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib3dvNV)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib3fvNV)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib3svNV)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib2dvNV)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib2fvNV)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib2svNV)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib1dvNV)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib1fvNV)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib1svNV)(GLuint,GLshort *);
GLvoid ( * glVertexAttribs4ubvNV)(GLuint,GLsizei,GLubyte *);
GLvoid ( * glVertexAttribs4dvNV)(GLuint,GLsizei,GLdouble *);
GLvoid ( * glVertexAttribs4fvNV)(GLuint,GLsizei,GLfloat *);
GLvoid ( * glVertexAttribs4svNV)(GLuint,GLsizei,GLshort *);
GLvoid ( * glVertexAttribs3dvNV)(GLuint,GLsizei,GLdouble *);
GLvoid ( * glVertexAttribs3fvNV)(GLuint,GLsizei,GLfloat *);
GLvoid ( * glVertexAttribs3svNV)(GLuint,GLsizei,GLshort *);
GLvoid ( * glVertexAttribs2dvNV)(GLuint,GLsizei,GLdouble *);
GLvoid ( * glVertexAttribs2fvNV)(GLuint,GLsizei,GLfloat *);
GLvoid ( * glVertexAttribs2svNV)(GLuint,GLsizei,GLshort *);
GLvoid ( * glVertexAttribs1dvNV)(GLuint,GLsizei,GLdouble *);
GLvoid ( * glVertexAttribs1fvNV)(GLuint,GLsizei,GLfloat *);
GLvoid ( * glVertexAttribs1svNV)(GLuint,GLsizei,GLshort *);
GLvoid ( * glGetVertexAttribdvNV)(GLuint,GLenum,GLdouble *);
GLvoid ( * glGetVertexAttribfvNV)(GLuint,GLenum,GLfloat *);
GLvoid ( * glGetVertexAttribivNV)(GLuint,GLenum,GLint *);
GLvoid ( * glTrackMatrixNV)(GLenum,GLuint,GLenum,GLenum);
GLvoid ( * glGetTrackMatrixivNV)(GLenum,GLuint,GLenum,GLint *);
GLvoid ( * glRequestResidentProgramsNV)(GLsizei, GLuint *);
GLboolean ( * glAreProgramsResidentNV)(GLsizei, const GLuint *, GLboolean *);
GLvoid ( * glGenOcclusionQueriesNV)(GLsizei,GLuint *);
GLvoid ( * glDeleteOcclusionQueriesNV)(GLsizei,const GLuint *);
GLboolean ( * glIsOcclusionQueryNV)(GLuint);
GLvoid ( * glBeginOcclusionQueryNV)(GLuint);
GLvoid ( * glEndOcclusionQueryNV)(void);
GLvoid ( * glGetOcclusionQueryivNV)(GLuint,GLenum,GLint *);
GLvoid ( * glGetOcclusionQueryuivNV)(GLuint,GLenum,GLuint *);
GLvoid ( * glPointParameteriNV)(GLenum,GLint);
GLvoid ( * glPointParameterivNV)(GLenum,const GLint *);
GLvoid ( * glProgramNamedParameter4dNV)(GLuint,GLsizei,const GLubyte *,GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glProgramNamedParameter4fNV)(GLuint,GLsizei,const GLubyte *,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glProgramNamedParameter4dvNV)(GLuint,GLsizei,const GLubyte *,const GLdouble *);
GLvoid ( * glProgramNamedParameter4fvNV)(GLuint,GLsizei,const GLubyte *,const GLfloat *);
GLvoid ( * glGetProgramNamedParameterdvNV)(GLuint,GLsizei,const GLubyte *,GLdouble *);
GLvoid ( * glGetProgramNamedParameterfvNV)(GLuint,GLsizei,const GLubyte *,GLfloat *);
GLvoid ( * glPrimitiveRestartNV)(void);
GLvoid ( * glPrimitiveRestartIndexNV)(GLuint);
GLvoid ( * glProgramLocalParameterI4iNV)(GLenum,GLuint,GLint,GLint,GLint,GLint);
GLvoid ( * glProgramLocalParameterI4uiNV)(GLenum,GLuint,GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glProgramEnvParameterI4iNV)(GLenum,GLuint,GLint,GLint,GLint,GLint);
GLvoid ( * glProgramEnvParameterI4uiNV)(GLenum,GLuint,GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glProgramLocalParameterI4ivNV)(GLenum,GLuint,const GLint *);
GLvoid ( * glProgramLocalParameterI4uivNV)(GLenum,GLuint,const GLuint *);
GLvoid ( * glProgramEnvParameterI4ivNV)(GLenum,GLuint,const GLint *);
GLvoid ( * glProgramEnvParameterI4uivNV)(GLenum,GLuint,const GLuint *);
GLvoid ( * glProgramLocalParametersI4ivNV)(GLenum,GLuint,GLuint,const GLint *);
GLvoid ( * glProgramLocalParametersI4uivNV)(GLenum,GLuint,GLuint,const GLuint *);
GLvoid ( * glProgramEnvParametersI4ivNV)(GLenum,GLuint,GLuint,const GLint *);
GLvoid ( * glProgramEnvParametersI4uivNV)(GLenum,GLuint,GLuint,const GLuint *);
GLvoid ( * glGetProgramLocalParameterIivNV)(GLenum,GLuint,GLint *);
GLvoid ( * glGetProgramLocalParameterIuivNV)(GLenum,GLuint,GLuint *);
GLvoid ( * glGetProgramEnvParameterIivNV)(GLenum,GLuint,GLint *);
GLvoid ( * glGetProgramEnvParameterIuivNV)(GLenum,GLuint,GLuint *);
GLvoid ( * glProgramVertexLimitNV)(GLenum,GLint);
GLvoid ( * glFramebufferTextureEXT)(GLenum,GLenum,GLuint,GLuint);
GLvoid ( * glFramebufferTextureLayerEXT)(GLenum,GLenum,GLuint,GLint,GLint);
GLvoid ( * glFramebufferTextureFaceEXT)(GLenum,GLenum,GLuint,GLint,GLenum);
GLvoid ( * glDepthRangedNV)(GLdouble,GLdouble);
GLvoid ( * glClearDepthdNV)(GLdouble);
GLvoid ( * glDepthBoundsdNV)(GLdouble,GLdouble);
GLvoid ( * glRenderbufferStorageMultisampleCoverageNV)(GLenum,GLsizei,GLsizei,GLenum,GLsizei,GLsizei);
GLvoid ( * glStringMarkerGREMEDY)(GLsizei,const void *);
GLvoid ( * glFrameTerminatorGREMEDY)(void);
GLvoid ( * glLoadTransposeMatrixfARB)(const GLfloat[]);
GLvoid ( * glLoadTransposeMatrixdARB)(const GLdouble[]);
GLvoid ( * glMultTransposeMatrixfARB)(const GLfloat[]);
GLvoid ( * glMultTransposeMatrixdARB)(const GLdouble[]);
GLvoid ( * glSampleCoverageARB)(GLclampf,GLboolean);
GLvoid ( * glPointParameterfARB)(GLenum,GLfloat);
GLvoid ( * glPointParameterfvARB)(GLenum,GLfloat *);
GLvoid ( * glWindowPos2dARB)(GLdouble,GLdouble);
GLvoid ( * glWindowPos2fARB)(GLfloat,GLfloat);
GLvoid ( * glWindowPos2iARB)(GLint,GLint);
GLvoid ( * glWindowPos2sARB)(GLshort,GLshort);
GLvoid ( * glWindowPos3dARB)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glWindowPos3fARB)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glWindowPos3iARB)(GLint,GLint,GLint);
GLvoid ( * glWindowPos3sARB)(GLshort,GLshort,GLshort);
GLvoid ( * glWindowPos2dvARB)(const GLdouble *);
GLvoid ( * glWindowPos2fvARB)(const GLfloat *);
GLvoid ( * glWindowPos2ivARB)(const GLint *);
GLvoid ( * glWindowPos2svARB)(const GLshort *);
GLvoid ( * glWindowPos3dvARB)(const GLdouble *);
GLvoid ( * glWindowPos3fvARB)(const GLfloat *);
GLvoid ( * glWindowPos3ivARB)(const GLint *);
GLvoid ( * glWindowPos3svARB)(const GLshort *);
GLvoid ( * glProgramStringARB)(GLenum,GLenum,GLsizei,const void *);
GLvoid ( * glGetProgramivARB)(GLenum,GLenum,GLint *);
GLvoid ( * glGetProgramStringARB)(GLenum,GLenum,void *string);
GLvoid ( * glGenProgramsARB)(GLsizei,GLuint *);
GLvoid ( * glDeleteProgramsARB)(GLsizei,const GLuint *);
GLvoid ( * glBindProgramARB)(GLenum,GLuint);
GLboolean ( * glIsProgramARB)(GLuint);
GLvoid ( * glEnableVertexAttribArrayARB)(GLuint);
GLvoid ( * glDisableVertexAttribArrayARB)(GLuint);
GLvoid ( * glVertexAttribPointerARB)(GLuint,GLint,GLenum,GLboolean,GLsizei,const GLvoid *);
GLvoid ( * glGetVertexAttribPointervARB)(GLuint,GLenum,GLvoid **);
GLvoid ( * glProgramEnvParameter4dARB)(GLenum,GLuint,GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glProgramEnvParameter4fARB)(GLenum,GLuint,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glProgramLocalParameter4dARB)(GLenum,GLuint,GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glProgramLocalParameter4fARB)(GLenum,GLuint,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glProgramEnvParameter4dvARB)(GLenum,GLuint,const GLdouble *);
GLvoid ( * glProgramEnvParameter4fvARB)(GLenum,GLuint,const GLfloat *);
GLvoid ( * glProgramLocalParameter4dvARB)(GLenum,GLuint,const GLdouble *);
GLvoid ( * glProgramLocalParameter4fvARB)(GLenum,GLuint,const GLfloat *);
GLvoid ( * glGetProgramEnvParameterdvARB)(GLenum,GLuint,GLdouble *);
GLvoid ( * glGetProgramEnvParameterfvARB)(GLenum,GLuint,GLfloat *);
GLvoid ( * glGetProgramLocalParameterdvARB)(GLenum,GLuint,GLdouble *);
GLvoid ( * glGetProgramLocalParameterfvARB)(GLenum,GLuint,GLfloat *);
GLvoid ( * glVertexAttrib1dARB)(GLuint,GLdouble);
GLvoid ( * glVertexAttrib1fARB)(GLuint,GLfloat);
GLvoid ( * glVertexAttrib1sARB)(GLuint,GLshort);
GLvoid ( * glVertexAttrib2dARB)(GLuint,GLdouble,GLdouble);
GLvoid ( * glVertexAttrib2fARB)(GLuint,GLfloat,GLfloat);
GLvoid ( * glVertexAttrib2sARB)(GLuint,GLshort,GLshort);
GLvoid ( * glVertexAttrib3dARB)(GLuint,GLdouble,GLdouble,GLdouble);
GLvoid ( * glVertexAttrib3fARB)(GLuint,GLfloat,GLfloat,GLfloat);
GLvoid ( * glVertexAttrib3sARB)(GLuint,GLshort,GLshort,GLshort);
GLvoid ( * glVertexAttrib4dARB)(GLuint,GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glVertexAttrib4fARB)(GLuint,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glVertexAttrib4sARB)(GLuint,GLshort,GLshort,GLshort,GLshort);
GLvoid ( * glVertexAttrib4NubARB)(GLuint,GLubyte,GLubyte,GLubyte,GLubyte);
GLvoid ( * glVertexAttrib4NbvARB)(GLuint,GLbyte *);
GLvoid ( * glVertexAttrib4NivARB)(GLuint,GLint *);
GLvoid ( * glVertexAttrib4NsvARB)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib4NubvARB)(GLuint,GLubyte *);
GLvoid ( * glVertexAttrib4NuivARB)(GLuint,GLuint *);
GLvoid ( * glVertexAttrib4NusvARB)(GLuint,GLushort *);
GLvoid ( * glVertexAttrib4uivARB)(GLuint,GLuint *);
GLvoid ( * glVertexAttrib4ubvARB)(GLuint,GLubyte *);
GLvoid ( * glVertexAttrib4usvARB)(GLuint,GLushort *);
GLvoid ( * glVertexAttrib4bvARB)(GLuint,GLbyte *);
GLvoid ( * glVertexAttrib4ivARB)(GLuint,GLint *);
GLvoid ( * glVertexAttrib4dvARB)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib4fvARB)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib4svARB)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib3dvARB)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib3fvARB)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib3svARB)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib2dvARB)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib2fvARB)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib2svARB)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib1dvARB)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib1fvARB)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib1svARB)(GLuint,GLshort *);
GLvoid ( * glGetVertexAttribdvARB)(GLuint,GLenum,GLdouble *);
GLvoid ( * glGetVertexAttribfvARB)(GLuint,GLenum,GLfloat *);
GLvoid ( * glGetVertexAttribivARB)(GLuint,GLenum,GLint *);
GLvoid ( * glGenQueriesARB)(GLsizei,GLuint *);
GLvoid ( * glDeleteQueriesARB)(GLsizei,const GLuint *);
GLboolean ( * glIsQueryARB)(GLuint);
GLvoid ( * glBeginQueryARB)(GLuint,GLuint);
GLvoid ( * glEndQueryARB)(GLenum);
GLvoid ( * glGetQueryivARB)(GLuint,GLenum,GLint *);
GLvoid ( * glGetQueryObjectivARB)(GLuint,GLenum,GLint *);
GLvoid ( * glGetQueryObjectuivARB)(GLuint,GLenum,GLuint *);
GLvoid ( * glDeleteObjectARB)(GLuint);
GLvoid ( * glDetachObjectARB)(GLuint,GLuint);
GLvoid ( * glCompileShaderARB)(GLuint);
GLvoid ( * glAttachObjectARB)(GLuint,GLuint);
GLvoid ( * glLinkProgramARB)(GLuint);
GLvoid ( * glUseProgramObjectARB)(GLuint);
GLvoid ( * glValidateProgramARB)(GLuint);
GLuint ( * glGetHandleARB)(GLenum);
GLuint ( * glCreateShaderObjectARB)(GLenum);
GLuint ( * glCreateProgramObjectARB)(void);
GLvoid ( * glShaderSourceARB)(GLuint,GLsizei,GLchar**,GLint *);
GLvoid ( * glUniform1fARB)(GLint,GLfloat);
GLvoid ( * glUniform2fARB)(GLint,GLfloat,GLfloat);
GLvoid ( * glUniform3fARB)(GLint,GLfloat,GLfloat,GLfloat);
GLvoid ( * glUniform4fARB)(GLint,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glUniform1iARB)(GLint,GLint);
GLvoid ( * glUniform2iARB)(GLint,GLint,GLint);
GLvoid ( * glUniform3iARB)(GLint,GLint,GLint,GLint);
GLvoid ( * glUniform4iARB)(GLint,GLint,GLint,GLint,GLint);
GLvoid ( * glUniform1fvARB)(GLint,GLsizei,const GLfloat *);
GLvoid ( * glUniform2fvARB)(GLint,GLsizei,const GLfloat *);
GLvoid ( * glUniform3fvARB)(GLint,GLsizei,const GLfloat *);
GLvoid ( * glUniform4fvARB)(GLint,GLsizei,const GLfloat *);
GLvoid ( * glUniform1ivARB)(GLint,GLsizei,const GLint *);
GLvoid ( * glUniform2ivARB)(GLint,GLsizei,const GLint *);
GLvoid ( * glUniform3ivARB)(GLint,GLsizei,const GLint *);
GLvoid ( * glUniform4ivARB)(GLint,GLsizei,const GLint *);
GLvoid ( * glUniformMatrix2fvARB)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glUniformMatrix3fvARB)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glUniformMatrix4fvARB)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glGetObjectParameterivARB)(GLuint,GLenum,GLint *);
GLvoid ( * glGetObjectParameterfvARB)(GLuint,GLenum,GLfloat *);
GLvoid ( * glGetInfoLogARB)(GLuint,GLsizei,GLsizei *,GLchar *);
GLvoid ( * glGetShaderSourceARB)(GLuint,GLsizei,GLsizei *,GLchar *);
GLvoid ( * glGetActiveUniformARB)(GLuint,GLuint,GLsizei,GLsizei*,GLint*,GLenum*,GLchar*);
GLvoid ( * glGetUniformfvARB)(GLuint,GLint,GLfloat *);
GLvoid ( * glGetUniformivARB)(GLuint,GLint,GLint *);
GLint ( * glGetUniformLocationARB)(GLuint,const GLchar*);
GLvoid ( * glGetAttachedObjectsARB)(GLuint,GLsizei,GLsizei *,GLuint *);
GLvoid ( * glBindAttribLocationARB)(GLuint,GLuint,GLchar *);
GLvoid ( * glGetActiveAttribARB)(GLuint,GLuint,GLsizei,GLsizei *,GLint *,GLenum *,GLchar *);
GLint ( * glGetAttribLocationARB)(GLuint,const GLchar*);
GLvoid ( * glClampColorARB)(GLenum,GLenum);
GLvoid ( * glBlendFuncSeparate)(GLenum,GLenum,GLenum,GLenum);
GLvoid ( * glFogCoordf)(GLfloat);
GLvoid ( * glFogCoordd)(GLdouble);
GLvoid ( * glPointParameteri)(GLenum,GLint);
GLvoid ( * glPointParameterf)(GLenum,GLfloat);
GLvoid ( * glSecondaryColor3b)(GLbyte,GLbyte,GLbyte);
GLvoid ( * glSecondaryColor3d)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glSecondaryColor3f)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glSecondaryColor3i)(GLint,GLint,GLint);
GLvoid ( * glSecondaryColor3s)(GLshort,GLshort,GLshort);
GLvoid ( * glSecondaryColor3ub)(GLubyte,GLubyte,GLubyte);
GLvoid ( * glSecondaryColor3ui)(GLuint,GLuint,GLuint);
GLvoid ( * glSecondaryColor3us)(GLushort,GLushort,GLushort);
GLvoid ( * glWindowPos2d)(GLdouble,GLdouble);
GLvoid ( * glWindowPos2f)(GLfloat,GLfloat);
GLvoid ( * glWindowPos2i)(GLint,GLint);
GLvoid ( * glWindowPos2s)(GLshort,GLshort);
GLvoid ( * glWindowPos3d)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glWindowPos3f)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glWindowPos3i)(GLint,GLint,GLint);
GLvoid ( * glWindowPos3s)(GLshort,GLshort,GLshort);
GLvoid ( * glFogCoordfv)(GLfloat *);
GLvoid ( * glFogCoorddv)(GLdouble *);
GLvoid ( * glFogCoordPointer)(GLenum,GLsizei,const GLvoid *);
GLvoid ( * glMultiDrawArrays)(GLenum,GLint*,GLsizei*,GLsizei);
GLvoid ( * glMultiDrawElements)(GLenum,const GLsizei *,GLenum,GLvoid **,GLsizei);
GLvoid ( * glPointParameterfv)(GLenum,GLfloat *);
GLvoid ( * glPointParameteriv)(GLenum,GLint *);
GLvoid ( * glSecondaryColor3bv)(GLbyte *);
GLvoid ( * glSecondaryColor3dv)(GLdouble *);
GLvoid ( * glSecondaryColor3fv)(GLfloat *);
GLvoid ( * glSecondaryColor3iv)(GLint *);
GLvoid ( * glSecondaryColor3sv)(GLshort *);
GLvoid ( * glSecondaryColor3uiv)(GLuint *);
GLvoid ( * glSecondaryColor3ubv)(GLubyte *);
GLvoid ( * glSecondaryColor3usv)(GLushort *);
GLvoid ( * glSecondaryColorPointer)(GLint,GLenum,GLsizei,const GLvoid *);
GLvoid ( * glWindowPos2dv)(GLdouble *);
GLvoid ( * glWindowPos2fv)(GLfloat *);
GLvoid ( * glWindowPos2iv)(GLint *);
GLvoid ( * glWindowPos2sv)(GLshort *);
GLvoid ( * glWindowPos3dv)(GLdouble *);
GLvoid ( * glWindowPos3fv)(GLfloat *);
GLvoid ( * glWindowPos3iv)(GLint *);
GLvoid ( * glWindowPos3sv)(GLshort *);
GLvoid ( * glBlendEquationSeparate)(GLenum,GLenum);
GLvoid ( * glStencilOpSeparate)(GLenum,GLenum,GLenum,GLenum);
GLvoid ( * glAttachShader)(GLuint,GLuint);
GLvoid ( * glCompileShader)(GLuint);
GLvoid ( * glDeleteProgram)(GLuint);
GLvoid ( * glDeleteShader)(GLuint);
GLvoid ( * glDetachShader)(GLuint,GLuint);
GLvoid ( * glDisableVertexAttribArray)(GLuint);
GLvoid ( * glEnableVertexAttribArray)(GLuint);
GLvoid ( * glLinkProgram)(GLuint);
GLvoid ( * glUseProgram)(GLuint);
GLvoid ( * glValidateProgram)(GLuint);
GLvoid ( * glStencilFuncSeparate)(GLenum,GLenum,GLint,GLuint);
GLvoid ( * glStencilMaskSeparate)(GLenum,GLuint);
GLuint ( * glCreateProgram)(void);
GLuint ( * glCreateShader)(GLenum);
GLboolean ( * glIsProgram)(GLuint);
GLboolean ( * glIsShader)(GLuint);
GLvoid ( * glUniform1f)(GLint,GLfloat);
GLvoid ( * glUniform1i)(GLint,GLint);
GLvoid ( * glUniform2f)(GLint,GLfloat,GLfloat);
GLvoid ( * glUniform2i)(GLint,GLint,GLint);
GLvoid ( * glUniform3f)(GLint,GLfloat,GLfloat,GLfloat);
GLvoid ( * glUniform3i)(GLint,GLint,GLint,GLint);
GLvoid ( * glUniform4f)(GLint,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glUniform4i)(GLint,GLint,GLint,GLint,GLint);
GLvoid ( * glVertexAttrib1d)(GLuint,GLdouble);
GLvoid ( * glVertexAttrib1f)(GLuint,GLfloat);
GLvoid ( * glVertexAttrib1s)(GLuint,GLshort);
GLvoid ( * glVertexAttrib2d)(GLuint,GLdouble,GLdouble);
GLvoid ( * glVertexAttrib2f)(GLuint,GLfloat,GLfloat);
GLvoid ( * glVertexAttrib2s)(GLuint,GLshort,GLshort);
GLvoid ( * glVertexAttrib3d)(GLuint,GLdouble,GLdouble,GLdouble);
GLvoid ( * glVertexAttrib3f)(GLuint,GLfloat,GLfloat,GLfloat);
GLvoid ( * glVertexAttrib3s)(GLuint,GLshort,GLshort,GLshort);
GLvoid ( * glVertexAttrib4d)(GLuint,GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glVertexAttrib4f)(GLuint,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glVertexAttrib4s)(GLuint,GLshort,GLshort,GLshort,GLshort);
GLvoid ( * glVertexAttrib4Nub)(GLuint,GLubyte,GLubyte,GLubyte,GLubyte);
GLvoid ( * glDrawBuffers)(GLsizei,GLenum *);
GLvoid ( * glBindAttribLocation)(GLuint,GLuint,GLchar *);
GLvoid ( * glGetProgramiv)(GLuint,GLenum,GLint *);
GLvoid ( * glGetActiveAttrib)(GLuint,GLuint,GLsizei,GLsizei *,GLint *,GLenum *,GLchar *);
GLvoid ( * glGetActiveUniform)(GLuint,GLuint,GLsizei,GLsizei*,GLint*,GLenum*,GLchar*);
GLvoid ( * glGetAttachedShaders)(GLuint,GLsizei,GLsizei *,GLuint *);
GLint ( * glGetAttribLocation)(GLuint, GLchar *);
GLvoid ( * glGetProgramInfoLog)(GLuint,GLsizei,GLsizei *,GLchar *);
GLvoid ( * glGetShaderiv)(GLuint,GLenum,GLint *);
GLvoid ( * glGetShaderInfoLog)(GLuint,GLsizei,GLsizei *,GLchar *);
GLvoid ( * glGetShaderSource)(GLuint,GLsizei,GLsizei *,GLchar *);
GLint ( * glGetUniformLocation)(GLuint,const GLchar*);
GLvoid ( * glGetUniformfv)(GLuint,GLint,GLfloat *);
GLvoid ( * glGetUniformiv)(GLuint,GLint,GLint *);
GLvoid ( * glGetVertexAttribdv)(GLuint,GLenum,GLdouble *);
GLvoid ( * glGetVertexAttribfv)(GLuint,GLenum,GLfloat *);
GLvoid ( * glGetVertexAttribiv)(GLuint,GLenum,GLint *);
GLvoid ( * glGetVertexAttribPointerv)(GLuint,GLenum,GLvoid **);
GLvoid ( * glShaderSource)(GLuint,GLsizei,GLchar**,GLint *);
GLvoid ( * glUniform1fv)(GLint,GLsizei,GLfloat *);
GLvoid ( * glUniform1iv)(GLint,GLsizei,GLint *);
GLvoid ( * glUniform2fv)(GLint,GLsizei,GLfloat *);
GLvoid ( * glUniform2iv)(GLint,GLsizei,GLint *);
GLvoid ( * glUniform3fv)(GLint,GLsizei,GLfloat *);
GLvoid ( * glUniform3iv)(GLint,GLsizei,GLint *);
GLvoid ( * glUniform4fv)(GLint,GLsizei,GLfloat *);
GLvoid ( * glUniform4iv)(GLint,GLsizei,GLint *);
GLvoid ( * glUniformMatrix2fv)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glUniformMatrix3fv)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glUniformMatrix4fv)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glVertexAttrib4Nbv)(GLuint,GLbyte *);
GLvoid ( * glVertexAttrib4Niv)(GLuint,GLint *);
GLvoid ( * glVertexAttrib4Nsv)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib4Nubv)(GLuint,GLubyte *);
GLvoid ( * glVertexAttrib4Nuiv)(GLuint,GLuint *);
GLvoid ( * glVertexAttrib4Nusv)(GLuint,GLushort *);
GLvoid ( * glVertexAttrib4uiv)(GLuint,GLuint *);
GLvoid ( * glVertexAttrib4ubv)(GLuint,GLubyte *);
GLvoid ( * glVertexAttrib4usv)(GLuint,GLushort *);
GLvoid ( * glVertexAttrib4bv)(GLuint,GLbyte *);
GLvoid ( * glVertexAttrib4iv)(GLuint,GLint *);
GLvoid ( * glVertexAttrib4dv)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib4fv)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib4sv)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib3dv)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib3fv)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib3sv)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib2dv)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib2fv)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib2sv)(GLuint,GLshort *);
GLvoid ( * glVertexAttrib1dv)(GLuint,GLdouble *);
GLvoid ( * glVertexAttrib1fv)(GLuint,GLfloat *);
GLvoid ( * glVertexAttrib1sv)(GLuint,GLshort *);
GLvoid ( * glVertexAttribPointer)(GLuint,GLint,GLenum,GLboolean,GLsizei,GLvoid *);
GLvoid ( * glAccum)(GLenum,GLfloat);
GLvoid ( * glAlphaFunc)(GLenum,GLclampf);
GLvoid ( * glArrayElement)(GLint);
GLvoid ( * glBindTexture)(GLenum,GLuint);
GLvoid ( * glBlendFunc)(GLenum,GLenum);
GLvoid ( * glCallList)(GLuint);
GLvoid ( * glClear)(GLbitfield);
GLvoid ( * glClearAccum)(GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glClearColor)(GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glClearDepth)(GLclampd);
GLvoid ( * glClearIndex)(GLfloat);
GLvoid ( * glClearStencil)(GLint);
GLvoid ( * glColor3b)(GLbyte,GLbyte,GLbyte);
GLvoid ( * glColor3d)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glColor3f)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glColor3i)(GLint,GLint,GLint);
GLvoid ( * glColor3s)(GLshort,GLshort,GLshort);
GLvoid ( * glColor3ub)(GLubyte,GLubyte,GLubyte);
GLvoid ( * glColor3ui)(GLuint,GLuint,GLuint);
GLvoid ( * glColor3us)(GLushort,GLushort,GLushort);
GLvoid ( * glColor4b)(GLbyte,GLbyte,GLbyte,GLbyte);
GLvoid ( * glColor4d)(GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glColor4f)(GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glColor4i)(GLint,GLint,GLint,GLint);
GLvoid ( * glColor4s)(GLshort,GLshort,GLshort,GLshort);
GLvoid ( * glColor4ub)(GLubyte,GLubyte,GLubyte,GLubyte);
GLvoid ( * glColor4ui)(GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glColor4us)(GLushort,GLushort,GLushort,GLushort);
GLvoid ( * glColorMask)(GLboolean,GLboolean,GLboolean,GLboolean);
GLvoid ( * glColorMaterial)(GLenum,GLenum);
GLvoid ( * glCopyPixels)(GLint,GLint,GLsizei,GLsizei,GLenum);
GLvoid ( * glCopyTexImage1D)(GLenum,GLint,GLenum,GLint,GLint,GLsizei,GLint);
GLvoid ( * glCopyTexImage2D)(GLenum,GLint,GLenum,GLint,GLint,GLsizei,GLsizei,GLint);
GLvoid ( * glCopyTexSubImage1D)(GLenum,GLint,GLint,GLint,GLint,GLsizei);
GLvoid ( * glCopyTexSubImage2D)(GLenum,GLint,GLint,GLint,GLint,GLint,GLsizei,GLsizei);
GLvoid ( * glCullFace)(GLenum);
GLvoid ( * glDeleteLists)(GLuint,GLuint);
GLvoid ( * glDepthFunc)(GLenum);
GLvoid ( * glDepthMask)(GLboolean);
GLvoid ( * glDepthRange)(GLclampd,GLclampd);
GLvoid ( * glDrawArrays)(GLenum,GLint,GLsizei);
GLvoid ( * glDrawBuffer)(GLenum);
GLvoid ( * glEdgeFlag)(GLboolean);
GLvoid ( * glEvalCoord1d)(GLdouble);
GLvoid ( * glEvalCoord1f)(GLfloat);
GLvoid ( * glEvalCoord2d)(GLdouble,GLdouble);
GLvoid ( * glEvalCoord2f)(GLfloat,GLfloat);
GLvoid ( * glEvalMesh1)(GLenum,GLint,GLint);
GLvoid ( * glEvalMesh2)(GLenum,GLint,GLint,GLint,GLint);
GLvoid ( * glEvalPoint1)(GLint);
GLvoid ( * glEvalPoint2)(GLint,GLint);
GLvoid ( * glFinish)(void);
GLvoid ( * glFlush)(void);
GLvoid ( * glFogi)(GLenum,GLint);
GLvoid ( * glFogf)(GLenum,GLfloat);
GLvoid ( * glFrontFace)(GLenum);
GLvoid ( * glFrustum)(GLdouble,GLdouble,GLdouble,GLdouble,GLdouble,GLdouble);
GLuint ( * glGenLists)(GLsizei);
GLvoid ( * glHint)(GLenum,GLenum);
GLvoid ( * glIndexd)(GLdouble);
GLvoid ( * glIndexf)(GLfloat);
GLvoid ( * glIndexi)(GLint);
GLvoid ( * glIndexMask)(GLuint);
GLvoid ( * glIndexs)(GLshort);
GLvoid ( * glIndexub)(GLubyte);
GLvoid ( * glInitNames)(void);
GLboolean ( * glIsEnabled)(GLenum);
GLboolean ( * glIsList)(GLuint);
GLboolean ( * glIsTexture)(GLuint);
GLvoid ( * glLightModelf)(GLenum,GLfloat);
GLvoid ( * glLightModeli)(GLenum,GLint);
GLvoid ( * glLightf)(GLenum,GLenum,GLfloat);
GLvoid ( * glLighti)(GLenum,GLenum,GLint);
GLvoid ( * glLineStipple)(GLint,GLushort);
GLvoid ( * glLineWidth)(GLfloat);
GLvoid ( * glListBase)(GLuint);
GLvoid ( * glLoadIdentity)(void);
GLvoid ( * glLoadName)(GLuint);
GLvoid ( * glLogicOp)(GLenum);
GLvoid ( * glMapGrid1d)(GLint,GLdouble,GLdouble);
GLvoid ( * glMapGrid1f)(GLint,GLfloat,GLfloat);
GLvoid ( * glMapGrid2d)(GLint,GLdouble,GLdouble,GLint,GLdouble,GLdouble);
GLvoid ( * glMapGrid2f)(GLint,GLfloat,GLfloat,GLint,GLfloat,GLfloat);
GLvoid ( * glMaterialf)(GLenum,GLenum,GLfloat);
GLvoid ( * glMateriali)(GLenum,GLenum,GLint);
GLvoid ( * glMatrixMode)(GLenum);
GLvoid ( * glNormal3b)(GLbyte,GLbyte,GLbyte);
GLvoid ( * glNormal3d)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glNormal3f)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glNormal3i)(GLint,GLint,GLint);
GLvoid ( * glNormal3s)(GLshort,GLshort,GLshort);
GLvoid ( * glOrtho)(GLdouble,GLdouble,GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glPassThrough)(GLfloat);
GLvoid ( * glPixelStoref)(GLenum,GLfloat);
GLvoid ( * glPixelStorei)(GLenum,GLint);
GLvoid ( * glPixelTransferf)(GLenum,GLfloat);
GLvoid ( * glPixelTransferi)(GLenum,GLint);
GLvoid ( * glPixelZoom)(GLfloat,GLfloat);
GLvoid ( * glPointSize)(GLfloat);
GLvoid ( * glPolygonMode)(GLenum,GLenum);
GLvoid ( * glPolygonOffset)(GLfloat,GLfloat);
GLvoid ( * glPopAttrib)(void);
GLvoid ( * glPopClientAttrib)(void);
GLvoid ( * glPopName)(void);
GLvoid ( * glPushAttrib)(GLbitfield);
GLvoid ( * glPushClientAttrib)(GLbitfield);
GLvoid ( * glPushName)(GLuint);
GLvoid ( * glRasterPos2d)(GLdouble,GLdouble);
GLvoid ( * glRasterPos2f)(GLfloat,GLfloat);
GLvoid ( * glRasterPos2i)(GLint,GLint);
GLvoid ( * glRasterPos2s)(GLshort,GLshort);
GLvoid ( * glRasterPos3d)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glRasterPos3f)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glRasterPos3i)(GLint,GLint,GLint);
GLvoid ( * glRasterPos3s)(GLshort,GLshort,GLshort);
GLvoid ( * glRasterPos4d)(GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glRasterPos4f)(GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glRasterPos4i)(GLint,GLint,GLint,GLint);
GLvoid ( * glRasterPos4s)(GLshort,GLshort,GLshort,GLshort);
GLvoid ( * glReadBuffer)(GLenum);
GLvoid ( * glRectd)(GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glRectf)(GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glRecti)(GLint,GLint,GLint,GLint);
GLvoid ( * glRects)(GLshort,GLshort,GLshort,GLshort);
GLint ( * glRenderMode)(GLenum);
GLvoid ( * glRotated)(GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glRotatef)(GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glScaled)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glScalef)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glScissor)(GLint,GLint,GLint,GLint);
GLvoid ( * glShadeModel)(GLenum);
GLvoid ( * glStencilFunc)(GLenum,GLint,GLuint);
GLvoid ( * glStencilMask)(GLuint);
GLvoid ( * glStencilOp)(GLenum,GLenum,GLenum);
GLvoid ( * glTexCoord1d)(GLdouble);
GLvoid ( * glTexCoord1f)(GLfloat);
GLvoid ( * glTexCoord1i)(GLint);
GLvoid ( * glTexCoord1s)(GLshort);
GLvoid ( * glTexCoord2d)(GLdouble,GLdouble);
GLvoid ( * glTexCoord2f)(GLfloat,GLfloat);
GLvoid ( * glTexCoord2i)(GLint,GLint);
GLvoid ( * glTexCoord2s)(GLshort,GLshort);
GLvoid ( * glTexCoord3d)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glTexCoord3f)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glTexCoord3i)(GLint,GLint,GLint);
GLvoid ( * glTexCoord3s)(GLshort,GLshort,GLshort);
GLvoid ( * glTexCoord4d)(GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glTexCoord4f)(GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glTexCoord4i)(GLint,GLint,GLint,GLint);
GLvoid ( * glTexCoord4s)(GLshort,GLshort,GLshort,GLshort);
GLvoid ( * glTexEnvf)(GLenum,GLenum,GLfloat);
GLvoid ( * glTexEnvi)(GLenum,GLenum,GLint);
GLvoid ( * glTexGend)(GLenum,GLenum,GLdouble);
GLvoid ( * glTexGenf)(GLenum,GLenum,GLfloat);
GLvoid ( * glTexGeni)(GLenum,GLenum,GLint);
GLvoid ( * glTexParameterf)(GLenum,GLenum,GLfloat);
GLvoid ( * glTexParameteri)(GLenum,GLenum,GLint);
GLvoid ( * glTranslated)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glTranslatef)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glVertex2d)(GLdouble,GLdouble);
GLvoid ( * glVertex2f)(GLfloat,GLfloat);
GLvoid ( * glVertex2i)(GLint,GLint);
GLvoid ( * glVertex2s)(GLshort,GLshort);
GLvoid ( * glVertex3d)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glVertex3f)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glVertex3i)(GLint,GLint,GLint);
GLvoid ( * glVertex3s)(GLshort,GLshort,GLshort);
GLvoid ( * glVertex4d)(GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glVertex4f)(GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glVertex4i)(GLint,GLint,GLint,GLint);
GLvoid ( * glVertex4s)(GLshort,GLshort,GLshort,GLshort);
GLvoid ( * glViewport)(GLuint,GLuint,GLuint,GLuint);
void ( * glEnable)(GLenum cap);
void ( * glDisable)(GLenum cap);
void ( * glEnableClientState)(GLenum cap);
void ( * glDisableClientState)(GLenum cap);
void ( * glBegin)(GLenum mode);
void ( * glEnd)(void);
void ( * glPopMatrix)(void);
void ( * glPushMatrix)(void);
void ( * glNewList)(GLuint list, GLenum mode);
void ( * glEndList)(void);
GLvoid ( * glCallLists)(GLsizei n, GLenum type, const GLvoid *lists);
void ( * glBitmap)(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
void ( * glEdgeFlagv)(const GLboolean *flag);
void ( * glIndexdv)(const GLdouble *c);
void ( * glIndexfv)(const GLfloat *c);
void ( * glIndexiv)(const GLint *c);
void ( * glIndexsv)(const GLshort *c);
void ( * glClipPlane)(GLenum plane, const GLdouble *equation);
void ( * glFogfv)(GLenum pname, const GLfloat *params);
void ( * glFogiv)(GLenum pname, const GLint *params);
void ( * glLightfv)(GLenum light, GLenum pname, const GLfloat *params);
void ( * glLightiv)(GLenum light, GLenum pname, const GLint *params);
void ( * glLightModelfv)(GLenum pname, const GLfloat *params);
void ( * glLightModeliv)(GLenum pname, const GLint *params);
void ( * glMaterialfv)(GLenum face, GLenum pname, const GLfloat *params);
void ( * glMaterialiv)(GLenum face, GLenum pname, const GLint *params);
void ( * glPolygonStipple)(const GLubyte *mask);
void ( * glTexParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
void ( * glTexParameteriv)(GLenum target, GLenum pname, const GLint *params);
void ( * glTexImage1D)(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void ( * glTexImage2D)(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void ( * glTexEnvfv)(GLenum target, GLenum pname, const GLfloat *params);
void ( * glTexEnviv)(GLenum target, GLenum pname, const GLint *params);
void ( * glTexGendv)(GLenum coord, GLenum pname, const GLdouble *params);
void ( * glTexGenfv)(GLenum coord, GLenum pname, const GLfloat *params);
void ( * glTexGeniv)(GLenum coord, GLenum pname, const GLint *params);
void ( * glFeedbackBuffer)(GLsizei size, GLenum type, GLfloat *buffer);
void ( * glSelectBuffer)(GLsizei size, GLuint *buffer);
void ( * glMap1d)(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
void ( * glMap1f)(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
void ( * glMap2d)(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
void ( * glMap2f)(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
void ( * glEvalCoord1dv)(const GLdouble *u);
void ( * glEvalCoord1fv)(const GLfloat *u);
void ( * glEvalCoord2dv)(const GLdouble *u);
void ( * glEvalCoord2fv)(const GLfloat *u);
void ( * glPixelMapfv)(GLenum map, GLsizei mapsize, const GLfloat *values);
void ( * glPixelMapuiv)(GLenum map, GLsizei mapsize, const GLuint *values);
void ( * glPixelMapusv)(GLenum map, GLsizei mapsize, const GLushort *values);
void ( * glReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
void ( * glDrawPixels)(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void ( * glGetClipPlane)(GLenum plane, GLdouble *equation);
void ( * glGetDoublev)(GLenum pname, GLdouble *params);
void ( * glGetIntegerv)(GLenum pname, GLint *params);
void ( * glGetFloatv)(GLenum pname, GLfloat *params);
void ( * glGetBooleanv)(GLenum pname, GLboolean *params);
void ( * glGetLightfv)(GLenum light, GLenum pname, GLfloat *params);
void ( * glGetLightiv)(GLenum light, GLenum pname, GLint *params);
void ( * glGetMapdv)(GLenum target, GLenum query, GLdouble *v);
void ( * glGetMapiv)(GLenum target, GLenum query, GLint *v);
void ( * glGetMapfv)(GLenum target, GLenum query, GLfloat *v);
void ( * glGetMaterialfv)(GLenum face, GLenum pname, GLfloat *params);
void ( * glGetMaterialiv)(GLenum face, GLenum pname, GLint *params);
void ( * glGetPixelMapfv)(GLenum map, GLfloat *values);
void ( * glGetPixelMapuiv)(GLenum map, GLuint *values);
void ( * glGetPixelMapusv)(GLenum map, GLushort *values);
void ( * glGetPolygonStipple)(GLubyte *mask);
const GLubyte * ( * glGetString)(GLenum name);
GLvoid ( * glGetTexEnvfv)(GLenum target, GLenum pname, GLfloat *params);
GLvoid ( * glGetTexEnviv)(GLenum target, GLenum pname, GLint *params);
GLvoid ( * glGetTexGendv)(GLenum coord, GLenum pname, GLdouble *params);
GLvoid ( * glGetTexGenfv)(GLenum coord, GLenum pname, GLfloat *params);
GLvoid ( * glGetTexGeniv)(GLenum coord, GLenum pname, GLint *params);
void ( * glGetTexImage)(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
void ( * glGetTexLevelParameteriv)(GLenum target, GLint level, GLenum pname, GLint *params);
void ( * glGetTexParameterfv)(GLenum target, GLenum pname, GLfloat *params);
void ( * glGetTexParameteriv)(GLenum target, GLenum pname, GLint *params);
void ( * glGetTexLevelParameterfv)(GLenum target, GLint level, GLenum pname, GLfloat *params);
void ( * glLoadMatrixf)(const GLfloat *m);
void ( * glLoadMatrixd)(const GLdouble *m);
void ( * glMultMatrixf)(const GLfloat *m);
void ( * glMultMatrixd)(const GLdouble *m);
GLvoid ( * glVertexPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr);
GLvoid ( * glColorPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr);
GLvoid ( * glTexCoordPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr);
void ( * glDrawElements)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
void ( * glEdgeFlagPointer)(GLsizei stride, const GLvoid *ptr);
void ( * glIndexPointer)(GLenum type, GLsizei stride, const GLvoid *ptr);
void ( * glInterleavedArrays)(GLenum format, GLsizei stride, const GLvoid *pointer);
void ( * glNormalPointer)(GLenum type, GLsizei stride, const GLvoid *ptr);
void ( * glTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
void ( * glTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
GLboolean ( * glAreTexturesResident)(GLsizei n, const GLuint *textures, GLboolean *residences);
GLvoid ( * glGenTextures)(GLsizei,GLuint *);
GLvoid ( * glDeleteTextures)(GLsizei,const GLuint *);
void ( * glPrioritizeTextures)(GLsizei n, const GLuint *textures, const GLclampf *priorities);
void ( * glIndexubv)(const GLubyte *c);
GLvoid ( * glTbufferMask3DFX)(GLuint);
GLvoid ( * glBeginConditionalRender)(GLuint,GLenum);
GLvoid ( * glEndConditionalRender)(void);
GLvoid ( * glVertexAttribI1i)(GLuint,GLint);
GLvoid ( * glVertexAttribI2i)(GLuint,GLint,GLint);
GLvoid ( * glVertexAttribI3i)(GLuint,GLint,GLint,GLint);
GLvoid ( * glVertexAttribI4i)(GLuint,GLint,GLint,GLint,GLint);
GLvoid ( * glVertexAttribI1ui)(GLuint,GLuint);
GLvoid ( * glVertexAttribI2ui)(GLuint,GLuint,GLuint);
GLvoid ( * glVertexAttribI3ui)(GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glVertexAttribI4ui)(GLuint,GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glVertexAttribI1iv)(GLuint,const GLint *);
GLvoid ( * glVertexAttribI2iv)(GLuint,const GLint *);
GLvoid ( * glVertexAttribI3iv)(GLuint,const GLint *);
GLvoid ( * glVertexAttribI4iv)(GLuint,const GLint *);
GLvoid ( * glVertexAttribI1uiv)(GLuint,const GLuint *);
GLvoid ( * glVertexAttribI2uiv)(GLuint,const GLuint *);
GLvoid ( * glVertexAttribI3uiv)(GLuint,const GLuint *);
GLvoid ( * glVertexAttribI4uiv)(GLuint,const GLuint *);
GLvoid ( * glVertexAttribI4bv)(GLuint,const GLbyte *);
GLvoid ( * glVertexAttribI4sv)(GLuint,const GLshort *);
GLvoid ( * glVertexAttribI4ubv)(GLuint,const GLubyte *);
GLvoid ( * glVertexAttribI4usv)(GLuint,const GLushort *);
GLvoid ( * glGetVertexAttribIiv)(GLuint,GLenum,GLint *);
GLvoid ( * glGetVertexAttribIuiv)(GLuint,GLenum,GLuint *);
GLvoid ( * glVertexAttribIPointer)(GLuint,GLint,GLenum,GLsizei,const GLvoid *);
GLvoid ( * glUniform1ui)(GLint,GLuint);
GLvoid ( * glUniform2ui)(GLint,GLuint,GLuint);
GLvoid ( * glUniform3ui)(GLint,GLuint,GLuint,GLuint);
GLvoid ( * glUniform4ui)(GLint,GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glUniform1uiv)(GLint,GLsizei,const GLuint *);
GLvoid ( * glUniform2uiv)(GLint,GLsizei,const GLuint *);
GLvoid ( * glUniform3uiv)(GLint,GLsizei,const GLuint *);
GLvoid ( * glUniform4uiv)(GLint,GLsizei,const GLuint *);
GLvoid ( * glGetUniformuiv)(GLuint,GLint,GLuint *);
GLvoid ( * glBindFragDataLocation)(GLuint,GLuint,const GLchar *);
GLint ( * glGetFragDataLocation)(GLuint,const GLchar *);
GLvoid ( * glClampColor)(GLenum,GLenum);
GLvoid ( * glDepthRanged)(GLdouble,GLdouble);
GLvoid ( * glClearDepthd)(GLdouble);
GLvoid ( * glDepthBoundsd)(GLdouble,GLdouble);
GLboolean ( * glIsRenderbuffer)(GLuint);
GLvoid ( * glBindRenderbuffer)(GLenum,GLuint);
GLvoid ( * glRenderbufferStorage)(GLenum,GLenum,GLsizei,GLsizei);
GLvoid ( * glGenRenderbuffers)(GLsizei,GLuint *);
GLvoid ( * glDeleteRenderbuffers)(GLsizei,const GLuint *);
GLvoid ( * glGetRenderbufferParameteriv)(GLenum,GLenum,GLint *);
GLvoid ( * glGenFramebuffers)(GLsizei,GLuint *);
GLvoid ( * glDeleteFramebuffers)(GLsizei,const GLuint *);
GLboolean ( * glIsFramebuffer)(GLuint);
GLvoid ( * glBindFramebuffer)(GLenum,GLuint);
GLenum ( * glCheckFramebufferStatus)(GLenum);
GLvoid ( * glFramebufferTexture1D)(GLenum,GLenum,GLenum,GLuint,GLint);
GLvoid ( * glFramebufferTexture2D)(GLenum,GLenum,GLenum,GLuint,GLint);
GLvoid ( * glFramebufferTexture3D)(GLenum,GLenum,GLenum,GLuint,GLint,GLint);
GLvoid ( * glFramebufferTextureLayer)(GLenum,GLenum,GLuint,GLint,GLint);
GLvoid ( * glFramebufferRenderbuffer)(GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glGetFramebufferAttachmentParameteriv)(GLenum,GLenum,GLenum,GLint *);
GLvoid ( * glGenerateMipmap)(GLenum);
GLvoid ( * glRenderbufferStorageMultisample)(GLenum,GLsizei,GLenum,GLsizei,GLsizei);
GLvoid ( * glBlitFramebuffer)(GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLbitfield,GLenum);
GLvoid ( * glClearColorIi)(GLint,GLint,GLint,GLint);
GLvoid ( * glClearColorIui)(GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glTexParameterIiv)(GLenum,GLenum,GLint *);
GLvoid ( * glTexParameterIuiv)(GLenum,GLenum,GLuint *);
GLvoid ( * glGetTexParameterIiv)(GLenum,GLenum,GLint *);
GLvoid ( * glGetTexParameterIuiv)(GLenum,GLenum,GLuint *);
GLvoid ( * glColorMaski)(GLuint,GLboolean,GLboolean,GLboolean,GLboolean);
GLvoid ( * glGetBooleani_v)(GLenum,GLenum,GLboolean *);
GLvoid ( * glGetIntegeri_v)(GLenum,GLenum,GLint *);
GLvoid ( * glEnablei)(GLenum,GLuint);
GLvoid ( * glDisablei)(GLenum,GLuint);
GLvoid ( * glIsEnabledi)(GLenum,GLuint);
GLvoid ( * glGenVertexArrays)(GLsizei,GLuint *);
GLvoid ( * glDeleteVertexArrays)(GLsizei,const GLuint *);
GLvoid ( * glBindVertexArray)(GLuint);
GLboolean ( * glIsVertexArray)(GLuint);
GLvoid ( * glActiveTexture)(GLenum);
GLvoid ( * glClientActiveTexture)(GLenum);
GLvoid ( * glMultiTexCoord1d)(GLenum,GLdouble);
GLvoid ( * glMultiTexCoord1f)(GLenum,GLfloat);
GLvoid ( * glMultiTexCoord1i)(GLenum,GLint);
GLvoid ( * glMultiTexCoord1s)(GLenum,GLshort);
GLvoid ( * glMultiTexCoord2d)(GLenum,GLdouble,GLdouble);
GLvoid ( * glMultiTexCoord2f)(GLenum,GLfloat,GLfloat);
GLvoid ( * glMultiTexCoord2i)(GLenum,GLint,GLint);
GLvoid ( * glMultiTexCoord2s)(GLenum,GLshort,GLshort);
GLvoid ( * glMultiTexCoord3d)(GLenum,GLdouble,GLdouble,GLdouble);
GLvoid ( * glMultiTexCoord3f)(GLenum,GLfloat,GLfloat,GLfloat);
GLvoid ( * glMultiTexCoord3i)(GLenum,GLint,GLint,GLint);
GLvoid ( * glMultiTexCoord3s)(GLenum,GLshort,GLshort,GLshort);
GLvoid ( * glMultiTexCoord4d)(GLenum,GLdouble,GLdouble,GLdouble,GLdouble);
GLvoid ( * glMultiTexCoord4f)(GLenum,GLfloat,GLfloat,GLfloat,GLfloat);
GLvoid ( * glMultiTexCoord4i)(GLenum,GLint,GLint,GLint,GLint);
GLvoid ( * glMultiTexCoord4s)(GLenum,GLshort,GLshort,GLshort,GLshort);
GLvoid ( * glSampleCoverage)(GLclampf,GLboolean);
GLvoid ( * glLoadTransposeMatrixf)(const float[]);
GLvoid ( * glLoadTransposeMatrixd)(const double[]);
GLvoid ( * glMultTransposeMatrixf)(const float[]);
GLvoid ( * glMultTransposeMatrixd)(const double[]);
GLvoid ( * glCompressedTexImage3D)(GLenum,GLint,GLenum,GLsizei,GLsizei,GLsizei,GLint,GLsizei,GLvoid*);
GLvoid ( * glCompressedTexImage2D)(GLenum,GLint,GLenum,GLsizei,GLsizei,GLint,GLsizei,GLvoid*);
GLvoid ( * glCompressedTexImage1D)(GLenum,GLint,GLenum,GLsizei,GLint,GLsizei,GLvoid*);
GLvoid ( * glCompressedTexSubImage3D)(GLenum,GLint,GLint,GLint,GLint,GLsizei,GLsizei,GLsizei,GLenum,GLsizei,GLvoid*);
GLvoid ( * glCompressedTexSubImage2D)(GLenum,GLint,GLint,GLint,GLsizei,GLsizei,GLenum,GLsizei,GLvoid*);
GLvoid ( * glCompressedTexSubImage1D)(GLenum,GLint,GLint,GLsizei,GLenum,GLsizei,GLvoid*);
GLvoid ( * glGetCompressedTexImage)(GLenum,GLint,GLvoid*);
GLvoid ( * glUniformMatrix2x3fv)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glUniformMatrix3x2fv)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glUniformMatrix2x4fv)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glUniformMatrix4x2fv)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glUniformMatrix3x4fv)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glUniformMatrix4x3fv)(GLint,GLsizei,GLboolean,GLfloat *);
GLvoid ( * glBlendColorEXT)(GLclampf,GLclampf,GLclampf,GLclampf);
GLvoid ( * glPolygonOffsetEXT)(GLfloat,GLfloat);
GLvoid ( * glGenTexturesEXT)(GLsizei,GLuint *);
GLvoid ( * glDeleteTexturesEXT)(GLsizei,const GLuint *);
GLvoid ( * glBindTextureEXT)(GLenum,GLint);
GLvoid ( * glPrioritizeTexturesEXT)(GLsizei,const GLuint *,const GLclampf *);
GLboolean ( * glAreTexturesResidentEXT)(GLsizei,const GLuint *,GLboolean *);
GLboolean ( * glIsTextureEXT)(GLuint);
GLvoid ( * glBlendEquationEXT)(GLenum);
GLvoid ( * glPointParameterfEXT)(GLenum,GLfloat);
GLvoid ( * glPointParameterfvEXT)(GLenum,GLfloat *);
GLvoid ( * glSecondaryColor3bEXT)(GLbyte,GLbyte,GLbyte);
GLvoid ( * glSecondaryColor3sEXT)(GLshort,GLshort,GLshort);
GLvoid ( * glSecondaryColor3iEXT)(GLint,GLint,GLint);
GLvoid ( * glSecondaryColor3fEXT)(GLfloat,GLfloat,GLfloat);
GLvoid ( * glSecondaryColor3dEXT)(GLdouble,GLdouble,GLdouble);
GLvoid ( * glSecondaryColor3ubEXT)(GLubyte,GLubyte,GLubyte);
GLvoid ( * glSecondaryColor3usEXT)(GLushort,GLushort,GLushort);
GLvoid ( * glSecondaryColor3uiEXT)(GLuint,GLuint,GLuint);
GLvoid ( * glSecondaryColor3bvEXT)(GLbyte *);
GLvoid ( * glSecondaryColor3dvEXT)(GLdouble *);
GLvoid ( * glSecondaryColor3fvEXT)(GLfloat *);
GLvoid ( * glSecondaryColor3ivEXT)(GLint *);
GLvoid ( * glSecondaryColor3svEXT)(GLshort *);
GLvoid ( * glSecondaryColor3uivEXT)(GLuint *);
GLvoid ( * glSecondaryColor3ubvEXT)(GLubyte *);
GLvoid ( * glSecondaryColor3usvEXT)(GLushort *);
GLvoid ( * glSecondaryColorPointerEXT)(GLint,GLenum,GLsizei,const GLvoid *);
GLvoid ( * glLockArraysEXT)(GLint,GLint);
GLvoid ( * glUnlockArraysEXT)(void);
GLvoid ( * glDrawRangeElementsEXT)(GLenum,GLuint,GLuint,GLsizei,GLenum,GLvoid*);
GLvoid ( * glMultiDrawArraysEXT)(GLenum,GLint*,GLsizei*,GLsizei);
GLvoid ( * glMultiDrawElementsEXT)(GLenum,const GLsizei *,GLenum,GLvoid **,GLsizei);
GLvoid ( * glFogCoordfEXT)(GLfloat);
GLvoid ( * glFogCoorddEXT)(GLdouble);
GLvoid ( * glFogCoordfvEXT)(GLfloat *);
GLvoid ( * glFogCoorddvEXT)(GLdouble *);
GLvoid ( * glFogCoordPointerEXT)(GLenum,GLsizei,const GLvoid *);
GLvoid ( * glBlendFuncSeparateEXT)(GLenum,GLenum,GLenum,GLenum);
GLvoid ( * glActiveStencilFaceEXT)(GLenum);
GLvoid ( * glDepthBoundsEXT)(GLclampd,GLclampd);
GLvoid ( * glBlendEquationSeparateEXT)(GLenum,GLenum);
GLboolean ( * glIsRenderbufferEXT)(GLuint);
GLvoid ( * glBindRenderbufferEXT)(GLenum,GLuint);
GLvoid ( * glRenderbufferStorageEXT)(GLenum,GLenum,GLsizei,GLsizei);
GLvoid ( * glGenRenderbuffersEXT)(GLsizei,GLuint *);
GLvoid ( * glDeleteRenderbuffersEXT)(GLsizei,const GLuint *);
GLvoid ( * glGetRenderbufferParameterivEXT)(GLenum,GLenum,GLint *);
GLvoid ( * glGenFramebuffersEXT)(GLsizei,GLuint *);
GLvoid ( * glDeleteFramebuffersEXT)(GLsizei,const GLuint *);
GLboolean ( * glIsFramebufferEXT)(GLuint);
GLvoid ( * glBindFramebufferEXT)(GLenum,GLuint);
GLenum ( * glCheckFramebufferStatusEXT)(GLenum);
GLvoid ( * glFramebufferTexture1DEXT)(GLenum,GLenum,GLenum,GLuint,GLint);
GLvoid ( * glFramebufferTexture2DEXT)(GLenum,GLenum,GLenum,GLuint,GLint);
GLvoid ( * glFramebufferTexture3DEXT)(GLenum,GLenum,GLenum,GLuint,GLint,GLint);
GLvoid ( * glFramebufferRenderbufferEXT)(GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glGetFramebufferAttachmentParameterivEXT)(GLenum,GLenum,GLenum,GLint *);
GLvoid ( * glGenerateMipmapEXT)(GLenum);
GLvoid ( * glStencilClearTagEXT)(GLsizei,GLuint);
GLvoid ( * glBlitFramebufferEXT)(GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLbitfield,GLenum);
GLvoid ( * glRenderbufferStorageMultisampleEXT)(GLenum,GLsizei,GLenum,GLsizei,GLsizei);
GLvoid ( * glGetQueryObjecti64vEXT)(GLuint,GLenum,GLint64 *);
GLvoid ( * glGetQueryObjectui64vEXT)(GLuint,GLenum,GLuint64 *);
GLvoid ( * glProgramEnvParameters4fvEXT)(GLenum,GLuint,GLsizei,const GLfloat *);
GLvoid ( * glProgramLocalParameters4fvEXT)(GLenum,GLuint,GLsizei,const GLfloat *);
GLvoid ( * glProgramParameteriEXT)(GLuint,GLenum,GLint);
GLvoid ( * glVertexAttribI1iEXT)(GLuint,GLint);
GLvoid ( * glVertexAttribI2iEXT)(GLuint,GLint,GLint);
GLvoid ( * glVertexAttribI3iEXT)(GLuint,GLint,GLint,GLint);
GLvoid ( * glVertexAttribI4iEXT)(GLuint,GLint,GLint,GLint,GLint);
GLvoid ( * glVertexAttribI1uiEXT)(GLuint,GLuint);
GLvoid ( * glVertexAttribI2uiEXT)(GLuint,GLuint,GLuint);
GLvoid ( * glVertexAttribI3uiEXT)(GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glVertexAttribI4uiEXT)(GLuint,GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glVertexAttribI1ivEXT)(GLuint,const GLint *);
GLvoid ( * glVertexAttribI2ivEXT)(GLuint,const GLint *);
GLvoid ( * glVertexAttribI3ivEXT)(GLuint,const GLint *);
GLvoid ( * glVertexAttribI4ivEXT)(GLuint,const GLint *);
GLvoid ( * glVertexAttribI1uivEXT)(GLuint,const GLuint *);
GLvoid ( * glVertexAttribI2uivEXT)(GLuint,const GLuint *);
GLvoid ( * glVertexAttribI3uivEXT)(GLuint,const GLuint *);
GLvoid ( * glVertexAttribI4uivEXT)(GLuint,const GLuint *);
GLvoid ( * glVertexAttribI4bvEXT)(GLuint,const GLbyte *);
GLvoid ( * glVertexAttribI4svEXT)(GLuint,const GLshort *);
GLvoid ( * glVertexAttribI4ubvEXT)(GLuint,const GLubyte *);
GLvoid ( * glVertexAttribI4usvEXT)(GLuint,const GLushort *);
GLvoid ( * glGetVertexAttribIivEXT)(GLuint,GLenum,GLint *);
GLvoid ( * glGetVertexAttribIuivEXT)(GLuint,GLenum,GLuint *);
GLvoid ( * glVertexAttribIPointerEXT)(GLuint,GLint,GLenum,GLsizei,const GLvoid *);
GLvoid ( * glUniform1uiEXT)(GLint,GLuint);
GLvoid ( * glUniform2uiEXT)(GLint,GLuint,GLuint);
GLvoid ( * glUniform3uiEXT)(GLint,GLuint,GLuint,GLuint);
GLvoid ( * glUniform4uiEXT)(GLint,GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glUniform1uivEXT)(GLint,GLsizei,const GLuint *);
GLvoid ( * glUniform2uivEXT)(GLint,GLsizei,const GLuint *);
GLvoid ( * glUniform3uivEXT)(GLint,GLsizei,const GLuint *);
GLvoid ( * glUniform4uivEXT)(GLint,GLsizei,const GLuint *);
GLvoid ( * glGetUniformuivEXT)(GLuint,GLint,GLuint *);
GLvoid ( * glBindFragDataLocationEXT)(GLuint,GLuint,const GLchar *);
GLint ( * glGetFragDataLocationEXT)(GLuint,const GLchar *);
GLvoid ( * glDrawArraysInstancedEXT)(GLenum,GLint,GLsizei,GLsizei);
GLvoid ( * glDrawElementsInstancedEXT)(GLenum,GLsizei,GLenum,const GLvoid *,GLsizei);
GLvoid ( * glTexBufferEXT)(GLenum,GLenum,GLenum);
GLvoid ( * glClearColorIiEXT)(GLint,GLint,GLint,GLint);
GLvoid ( * glClearColorIuiEXT)(GLuint,GLuint,GLuint,GLuint);
GLvoid ( * glTexParameterIivEXT)(GLenum,GLenum,GLint *);
GLvoid ( * glTexParameterIuivEXT)(GLenum,GLenum,GLuint *);
GLvoid ( * glGetTexParameterIivEXT)(GLenum,GLenum,GLint *);
GLvoid ( * glGetTexParameterIuivEXT)(GLenum,GLenum,GLuint *);
GLvoid ( * glDrawBuffersATI)(GLsizei,const GLenum *);
    };
    #endif
