# -*- ruby -*-

# Copyright (C) 2006 John M. Gabriele <jmg3000@gmail.com>
#
# This program is distributed under the terms of the MIT license.
# See the included COPYRIGHT file for the terms of this license.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Simple Rakefile for building rbogl.c.

require 'rake/clean'
require 'rbconfig'

INCLUDES = "-I#{Config::CONFIG['archdir']}"
CFLAGS   = "#{Config::CONFIG['CFLAGS']}"
CC       = "#{Config::CONFIG['CC']}"
O        = "#{Config::CONFIG['OBJEXT']}"

case RUBY_PLATFORM
when /darwin/
    INCLUDES << ' -F/System/Library/Frameworks'
when /mswin32/
    CFLAGS << ' -DWIN32'
end

CLEAN.include( '*.#{O}' )

SRC = FileList[ '*.c' ]
OBJ = SRC.ext( O )

task :default => OBJ
file 'rbogl.c' => [ 'rbogl.h' ]

rule ".#{O}" => '.c' do |t|
    sh "#{CC} -c #{CFLAGS} #{INCLUDES} #{t.source}"
end
